### PR TITLE
Update DOI links to preferred format

### PR DESCRIPTION
**Pull request by dhimmel**

### CODE REVIEW

**Comment by ethanwhite** [comment]
Thanks @dhimmel!!!

**Comment by ethanwhite** [comment]
I really appreciate all of your work over the last week. If you're interested I'd be happy to add you as a maintainer.

**Comment by dhimmel** [comment]
> If you're interested I'd be happy to add you as a maintainer.

Sure! Happy to review and merge PRs that are within my area of expertise as time permits.

**Comment by ethanwhite** [comment]
Awesome! Just invited you to the maintainers team.

**Pull request merged**
