### PR TITLE
Added two proposals. Hopefully this will build on site preview...

### PR DESCRIPTION
**Pull request by trashbirdecology**

### CODE REVIEW

**Comment by trashbirdecology** [comment]
yeah, idk wtf is going on here, sorry.

**Comment by ethanwhite** [comment]
Sorry I haven't had a chance to look at this. The title with the colon in it needed quotes, which I've added. I've tested locally so just going to make sure it builds on netlify and then I'll get this merged! Thanks for the contribution and sorry it turned out to be a hassle!

**Comment by ethanwhite** [comment]
And in it goes!

**Comment by ethanwhite** [comment]
And just fixed the link issue separately. `link` can be provided on it's own as just a url. If `link_name` is also there they (apparently) both have to be lists. Will put fixing this on the To Do list.

**Pull request merged**
